# Week 1 Solutions

In [47]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


## Problem 1 Solution

In [48]:
arr = np.random.randint(1,50, size = (5,4))
print(arr)

[[ 1 41 18 23]
 [36 17 35 14]
 [26 12 37 36]
 [47 48 32 25]
 [46 22 26 30]]


In [49]:
# extracting anti-diagonal elements
anti_diag = np.array([arr[i, arr.shape[1]-i-1] for i in range(arr.shape[1])])
print(anti_diag)

[23 35 12 47]


In [50]:
print(np.max(arr, axis = 1)) # max elements along the row

[41 36 37 48 46]


In [51]:
print(np.mean(arr)) # mean of all elements

28.6


In [52]:
new_arr = arr[arr <= np.mean(arr)] # new array with all the elements less than or equal to mean
print(new_arr)

[ 1 18 23 17 14 26 12 25 22 26]


In [53]:
def numpy_boundary_transversal(matrix):
    shape = matrix.shape
    lst1 = matrix[0, :].tolist()
    lst2 = (matrix[shape[0]-1, :].tolist())[::-1]
    lst3 = matrix[1:shape[0]-1, shape[1]-1].tolist()
    lst4 = (matrix[1:shape[0]-1, 0].tolist())[::-1]
    return lst1 + lst3 + lst2 + lst4
    
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(numpy_boundary_transversal(matrix))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 6, 9, 8, 7, 4]


## Problem 2 Solution

In [54]:
arr2 = np.random.uniform(0, 10, size = 20)
print(arr2)

[4.86774619 2.59039787 1.44555359 5.56597399 6.11231393 7.98169127
 5.52745337 6.19273246 5.57163733 1.21198696 0.8329545  3.75354434
 4.26331462 1.7735707  6.64860286 2.88631887 6.23039169 4.31327521
 3.63799458 9.75903661]


In [55]:
rounded = np.round(arr2, decimals = 2)
print(rounded)

[4.87 2.59 1.45 5.57 6.11 7.98 5.53 6.19 5.57 1.21 0.83 3.75 4.26 1.77
 6.65 2.89 6.23 4.31 3.64 9.76]


In [56]:
print(f"Maximum of array is: {np.max(rounded)} ")
print(f"Minimum of array is: {np.min(rounded)} ")
print(f"Median of array is: {np.median(rounded)} ")

Maximum of array is: 9.76 
Minimum of array is: 0.83 
Median of array is: 4.59 


In [57]:
# replacing all elements less than 5 by their squares
less_than = np.where(rounded < 5 , rounded**2, rounded)
print(less_than)

[23.7169  6.7081  2.1025  5.57    6.11    7.98    5.53    6.19    5.57
  1.4641  0.6889 14.0625 18.1476  3.1329  6.65    8.3521  6.23   18.5761
 13.2496  9.76  ]


In [58]:
# function that take an 1d array as input and return an alternate sorted array as 1st element as shortest, 2nd is largest, 3rd is 2nd smallest, 4th is 2nd largest and so on
def numpy_alternate_sort(array):
    array.sort()
    opt = []
    i = 0
    j = array.shape[0]-1
    while(i <j):
        opt.append(array[i])
        opt.append(array[j])
        i +=1
        j -=1
    if (array.shape[0])%2 ==0:
        return np.array(opt)
    else:
        opt.append(array[i])
        return np.array(opt)
        
array = np.array([1,6,3,9,10,12,5,4])  
print(numpy_alternate_sort(array))

[ 1 12  3 10  4  9  5  6]


## Problem 3 Solution

In [59]:
df = pd.DataFrame({"Name": ["S1", "S2", "S3", "S4", "S5", "S6","S7", "S8","S9","S10"],
                  "Subject" : ["Math", "CS", "Physics", "Chem", "Math", "CS", "Chem", "CS", "Physics", "Math"],
                  "Score" : np.random.randint(50, 100, size = 10).tolist(),
                  "Grade" : np.array([""]*10, dtype = object)})
display(df)

Name  Subject  Score Grade
0   S1     Math     61      
1   S2       CS     88      
2   S3  Physics     86      
3   S4     Chem     80      
4   S5     Math     96      
5   S6       CS     92      
6   S7     Chem     67      
7   S8       CS     95      
8   S9  Physics     69      
9  S10     Math     56

In [60]:
# Define conditions and corresponding grades
conditions = [
    (df['Score'] >= 90),
    (df['Score'] >= 80) & (df['Score'] < 90),
    (df['Score'] >= 70) & (df['Score'] < 80),
    (df['Score'] >= 60) & (df['Score'] < 70),
    (df['Score'] < 60)
]

grades = ['A', 'B', 'C', 'D', 'F']

# Assign grades
df['Grade'] = np.select(conditions, grades, default='F') 

# Display result
display(df)

Name  Subject  Score Grade
0   S1     Math     61     D
1   S2       CS     88     B
2   S3  Physics     86     B
3   S4     Chem     80     B
4   S5     Math     96     A
5   S6       CS     92     A
6   S7     Chem     67     D
7   S8       CS     95     A
8   S9  Physics     69     D
9  S10     Math     56     F

In [61]:
df = df.sort_values(by = "Score", ascending = False, ignore_index = True)
display(df)

Name  Subject  Score Grade
0   S5     Math     96     A
1   S8       CS     95     A
2   S6       CS     92     A
3   S2       CS     88     B
4   S3  Physics     86     B
5   S4     Chem     80     B
6   S9  Physics     69     D
7   S7     Chem     67     D
8   S1     Math     61     D
9  S10     Math     56     F

In [62]:
subject_avg_df = df.groupby("Subject", as_index=False)["Score"].mean()
display(subject_avg_df)

Subject      Score
0       CS  91.666667
1     Chem  73.500000
2     Math  71.000000
3  Physics  77.500000

In [63]:
print(np.array(df["Score"]))

[96 95 92 88 86 80 69 67 61 56]


In [64]:
def pandas_filter_pass(dataframe):
    df2 = dataframe[(dataframe["Grade"] == "A") | (dataframe["Grade"] == "B")]
    return df2
df2 = pandas_filter_pass(df)
print(df2)

  Name  Subject  Score Grade
0   S5     Math     96     A
1   S8       CS     95     A
2   S6       CS     92     A
3   S2       CS     88     B
4   S3  Physics     86     B
5   S4     Chem     80     B


## Problem 4 Solution

In [65]:
import pandas as pd
import random

# Sample templates
positive_templates = [
    "Absolutely loved it!",
    "A fantastic experience from start to finish.",
    "Great acting and brilliant storyline.",
    "One of the best movies I've seen this year.",
    "Incredible direction and cinematography.",
    "A masterpiece. Would highly recommend.",
    "Emotionally moving and beautifully shot.",
    "Engaging, entertaining, and very well made.",
    "Excellent pacing and character development.",
    "An unforgettable cinematic journey.",
    "Loved every minute of it.",
    "The plot was thrilling and unpredictable.",
    "The cast did a phenomenal job.",
    "A perfect blend of drama and action.",
    "Hilarious and heartfelt at the same time.",
    "Simply amazing. I'd watch it again!",
    "Beautifully executed.",
    "A must-watch for everyone.",
    "Outstanding performance by the lead actor.",
    "This movie exceeded my expectations.",
    "A solid 10 out of 10!",
    "Top-notch production value.",
    "A delight to watch.",
    "The emotional scenes hit hard.",
    "Visually stunning and thought-provoking.",
]

negative_templates = [
    "Terribly disappointing.",
    "A complete waste of time.",
    "Poor acting and weak storyline.",
    "I expected much more from this movie.",
    "Failed to impress in any aspect.",
    "The plot was slow and boring.",
    "Couldn’t finish it. It was that bad.",
    "Flat characters and meaningless dialogue.",
    "Not worth the hype.",
    "Disjointed scenes and lazy writing.",
    "Predictable and dull.",
    "Felt like a bad TV episode.",
    "Unconvincing performances.",
    "The script was all over the place.",
    "I kept waiting for it to get better, it didn’t.",
    "Nothing memorable at all.",
    "Sloppy editing ruined it.",
    "Forgettable and bland.",
    "Regret watching this.",
    "It dragged on forever.",
    "Bad CGI and worse acting.",
    "Totally underwhelming.",
    "No chemistry between the leads.",
    "Tried to be deep, but failed.",
    "One of the worst movies I’ve seen.",
]

# Duplicate and randomize to make 50 each
positive_reviews = random.choices(positive_templates, k=50)
negative_reviews = random.choices(negative_templates, k=50)

# Combine and label
reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

# Shuffle the dataset
combined = list(zip(reviews, sentiments))
random.shuffle(combined)

# Create DataFrame
df = pd.DataFrame(combined, columns=['Review', 'Sentiment'])

# Display a few samples
display(df)



Review Sentiment
0       One of the best movies I've seen this year.  positive
1                     Tried to be deep, but failed.  negative
2                   Poor acting and weak storyline.  negative
3              Couldn’t finish it. It was that bad.  negative
4                         Bad CGI and worse acting.  negative
..                                              ...       ...
95                           Forgettable and bland.  negative
96                          Terribly disappointing.  negative
97  I kept waiting for it to get better, it didn’t.  negative
98       Outstanding performance by the lead actor.  positive
99           A masterpiece. Would highly recommend.  positive

[100 rows x 2 columns]

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer


In [67]:
X = df["Review"]
y = df["Sentiment"]
vector = CountVectorizer(max_features = 500, stop_words = 'english') # as lowercase is already true no need to mention it
X = vector.fit_transform(X)
print(X.shape)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)


(100, 119)


In [68]:
model = Pipeline([
    ("Model", MultinomialNB())
])
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print(predictions)
accuracy = accuracy_score(predictions, y_test)
print(f"Accuracy: {accuracy*100}%")

['negative' 'negative' 'negative' 'positive' 'positive' 'negative'
 'negative' 'negative' 'positive' 'positive' 'negative' 'positive'
 'negative' 'negative' 'negative' 'negative' 'negative' 'negative'
 'positive' 'negative']
Accuracy: 85.0%


In [69]:
def predict_review_sentiment(trained_model, fitted_vectorizer, test_string):
    test = fitted_vectorizer.transform([test_string])
    y_pred = trained_model.predict(test)
    return y_pred[0]

s = "That movie was really bad, i don't prefer it anyone"
y_pred = predict_review_sentiment(model, vector, s)
print(y_pred)

negative


## Problem 5 Solution

In [70]:
import pandas as pd
import random

# Example positive and negative feedback phrases
good_phrases = [
    "Excellent product", "Very satisfied", "Loved it", "Highly recommended", "Amazing experience",
    "Works perfectly", "Great value", "Top-notch quality", "Five stars", "Will buy again",
    "Superb performance", "Exceeded expectations", "Fantastic!", "Very happy with it", "Best purchase ever",
    "Just what I needed", "Reliable and efficient", "Great customer service", "User-friendly", "Awesome build quality",
    "Fast delivery", "Perfect fit", "Exactly as described", "Good packaging", "Affordable and good",
    "Top quality", "Smooth operation", "Beautiful design", "Super useful", "Nothing to complain about",
    "Very intuitive", "Product met all my needs", "Sturdy and well-made", "Looks great", "Easy to set up",
    "Amazing durability", "Really impressed", "Battery lasts long", "Stylish and practical", "Very effective",
    "Performs better than expected", "Nice and compact", "Pleasant experience", "Just perfect", "Efficient and sleek",
    "Feels premium", "Simply awesome", "Love the features", "Flawless", "Beyond expectations"
]

bad_phrases = [
    "Terrible experience", "Very disappointed", "Broke after one use", "Would not recommend", "Poor quality",
    "Didn’t work", "Not worth the money", "Worst product", "One star", "Never buying again",
    "Slow delivery", "Not as described", "Cheap material", "Waste of money", "Stopped working soon",
    "Hard to use", "Poor customer service", "Overpriced", "Useless", "Looks different from photo",
    "Too complicated", "No instructions included", "Bad packaging", "Product arrived damaged", "Low durability",
    "Difficult to install", "Does not do what it claims", "Unreliable", "Bad design", "Too noisy",
    "Missing parts", "Doesn't fit properly", "Feels flimsy", "Very slow", "Buttons don’t work",
    "Battery drains fast", "Not intuitive", "Disappointed with the quality", "Looks cheap", "Very annoying",
    "Uncomfortable", "Not user-friendly", "Regret buying it", "Barely works", "Returned it immediately",
    "Overheats quickly", "Feels like a toy", "No value for money", "Subpar build", "Bad experience"
]

# Randomly shuffle the lists
random.shuffle(good_phrases)
random.shuffle(bad_phrases)

# Create DataFrame
reviews = good_phrases[:50] + bad_phrases[:50]
labels = ['good'] * 50 + ['bad'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': labels})

# Optional: shuffle rows
df = df.sample(frac=1).reset_index(drop=True)

# Display dataframe
display(df)


Review Sentiment
0          Not user-friendly       bad
1             Low durability       bad
2     Reliable and efficient      good
3          Overheats quickly       bad
4   Product met all my needs      good
..                       ...       ...
95                Overpriced       bad
96                Fantastic!      good
97            Waste of money       bad
98             Missing parts       bad
99                  One star       bad

[100 rows x 2 columns]

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

In [83]:
X = df["Review"]
y = df["Sentiment"]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state = 1)
model = Pipeline([
    ("vector", TfidfVectorizer(max_features = 300, stop_words = 'english')),
    ("Linear", LogisticRegression(max_iter = 200))
])
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(pred)

['good' 'good' 'good' 'good' 'good' 'good' 'good' 'good' 'bad' 'good'
 'good' 'bad' 'good' 'good' 'good' 'good' 'bad' 'good' 'good' 'bad' 'good'
 'bad' 'bad' 'good' 'good']


In [84]:
recall = recall_score(y_test, pred, pos_label='good')
precision = precision_score( y_test, pred, pos_label='good')
f1 = f1_score(y_test, pred, pos_label='good')

print(f"Recall Score: {recall}")
print(f"Precision Score: {precision}")
print(f"F1 Score: {f1}")

Recall Score: 0.75
Precision Score: 0.47368421052631576
F1 Score: 0.5806451612903226


In [85]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))


              precision    recall  f1-score   support

         bad       0.50      0.23      0.32        13
        good       0.47      0.75      0.58        12

    accuracy                           0.48        25
   macro avg       0.49      0.49      0.45        25
weighted avg       0.49      0.48      0.44        25



In [86]:
def text_preprocess_vectorize(list_texts, fitted_vectorizer):
    return fitted_vectorizer.transform(list_texts)

reviews = ["Valuable for price", "Good product"]
fit = text_preprocess_vectorize(reviews, vector)
print(fit)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 0 stored elements and shape (2, 119)>
